
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oelghoaiuvjhywlzldkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lbGdob2FpdXZqaHl3bHpsZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDIxNjcsImV4cCI6MjA2MTI3ODE2N30.OBX9YYpRFi673ckRHjM0k_yjWl1xBpRM4FY_oJjapWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
